server:
  port: 7003
spring:
  application:
    name: his-registry
eureka:
  instance:
     hostname: his-registry03.com
     prefer-ip-address: false #true代表使用IP地址的形式来定义注册中心的地址
  client:
    fetch-registry: true
    register-with-eureka: false  # 是否注册自己
    service-url:
      defaultZone: http://his-registry01.com:7001/eureka/,http://his-registry02.com:7002/eureka/